on:
  release:
    types: [published]
name: Deploy Extension
jobs:
  Publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install
      uses: actions/setup-node@v4
      with:
        node-version: latest
        check-latest: false
        cache: npm
        token: ${{ secrets.VSCE_TOKEN }}
    - run: npm install --unsafe-perm
    - name: Publish
      uses: lannonbr/vsce-action@3.0.0
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      with:
        args: publish -p $VSCE_TOKEN
